- name: Install MesloLG (Nerd Font)
  shell: |
    cd /tmp
    curl -LO https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/Meslo.zip
    unzip Meslo.zip -d Meslo
    cp Meslo/*.ttf ~/Library/Fonts
    rm -rf Meslo.zip Meslo
  args:
    creates: ~/Library/Fonts/Meslo*

- name: Install starship (custom prompt)
  homebrew:
    name: starship

- name: Check if Alacritty is already installed
  shell: test -d /Applications/Alacritty.app
  failed_when: false
  register: alacritty_installed

- name: Install Alacritty
  homebrew_cask:
    name: alacritty
  when: alacritty_installed.rc != 0
