- import_tasks: tasks/flameshot.yaml
- import_tasks: tasks/google-chrome.yaml
- import_tasks: tasks/hammerspoon.yaml
- import_tasks: tasks/programming-languages.yaml
- import_tasks: tasks/system-settings.yaml
- import_tasks: tasks/terminal.yaml
- import_tasks: tasks/vault-files.yaml
- import_tasks: tasks/window-manager.yaml
- import_tasks: tasks/nfa.yaml
