- name: Check if Discord is already installed
  shell: test -d /Applications/Discord.app
  failed_when: false
  register: discord_installed

- name: Install Discord
  homebrew_cask:
    name: Discord
  when: discord_installed.rc != 0
