#!/usr/bin/env bash
# Decrypt all files marked with ansible-vault filter in .vaultfiles

if [ ! -f ".vaultfiles" ]; then
  # No file list to encrypt/decrypt, move on...
  exit 0
fi

FILES=$(awk '$1' .vaultfiles)
FILES_TO_DECRYPT=()

for f in $FILES; do
  if [ ! -f "$f" ]; then
    echo "File $f does not exist, skipping..."
    continue
  fi

  # Check if the file is encrypted
  if grep -q '^\$ANSIBLE_VAULT;' "$f"; then
    FILES_TO_DECRYPT+=("$f")
  else
    echo "$f is already decrypted."
  fi
done

if [ ${#FILES_TO_DECRYPT[@]} -gt 0 ]; then
  echo "Decrypting: ${FILES_TO_DECRYPT[*]}"

  # Check if any file includes ssh/ in the path
  ssh_files_found=false
  for file in "${FILES_TO_DECRYPT[@]}"; do
    if [[ "$file" =~ ssh/ ]]; then
      ssh_files_found=true
      break
    fi
  done
  
  if [ "$ssh_files_found" = true ]; then
    ansible-vault decrypt "${FILES_TO_DECRYPT[@]}" --ask-vault-pass
  else
    ansible-vault decrypt "${FILES_TO_DECRYPT[@]}" --vault-password-file <(vault-from-op)
  fi

else
  echo "No files needed decryption"
fi