#!/usr/bin/env bash
# Encrypt stdin with ansible-vault, output to stdout

TMP=$(mktemp /tmp/gitcrypt-enc.XXXXXX)
trap 'rm -f "$TMP"' EXIT

cat > "$TMP"

# ansible-vault encrypt normally overwrites in-place,
# but we force output to stdout with --output -
ansible-vault encrypt --output - "$TMP"