- hosts: localhost
  tasks:
    - import_tasks: tasks/system-settings.yaml
      tags: system-settings
    - import_tasks: tasks/1password.yaml
      tags: 1password
    - import_tasks: tasks/window-manager.yaml
      tags: window-manager
    - import_tasks: tasks/terminal.yaml
      tags: terminal
    - import_tasks: tasks/zsh.yaml
      tags: zsh
    - import_tasks: tasks/productivity.yaml
      tags: productivity
    - import_tasks: tasks/neovim.yaml
      tags: neovim
    - import_tasks: tasks/vscode.yaml
      tags: vscode
    - import_tasks: tasks/cursor.yaml
      tags: cursor
    - import_tasks: tasks/node.yaml
      tags: node
